apiVersion: v1
kind: Service
metadata:
  name: devops-group2-database-service
spec:
  selector:
    app: devops-group2-database
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017