apiVersion: v1
kind: Service
metadata:
  name: devopsg2-k8s-service
spec:
  selector:
    app: devopsg2-k8s
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
